// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppLogger.h"
#include <Rcpp.h>

using namespace Rcpp;

// test_threads
void test_threads();
RcppExport SEXP RcppLogger_test_threads() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_threads();
    return R_NilValue;
END_RCPP
}
